const dynamicFormArray = (dataArray) => {
  form = {
    form: {
      required: false,
      method: "post",
      action: (dataArray.action !== undefined) ? dataArray.action : '',
      autocomplete: "off",
      //novalidate: "novalidate",
      class: "form-horizontal",
      enctype: "multipart/form-data",
    },
    _id: {
      required: false,
      value: ('_id' in dataArray.formData) ? dataArray.formData._id : '',
      fieldType: "hidden",
      id: "hexadecimal_id",
      name: "_id",
    },
    id: {
      required: true,
      value: ('id' in dataArray.formData) ? dataArray.formData.id : '',
      fieldType: "hidden",
      label: "Id",
      id: "cat_id",
      class: "form-control1",
      name: "id",
      placeholder: "",
    },
    parentId: {
      required: true,
      value: ('parentId' in dataArray.formData) ? dataArray.formData.parentId : '',
      fieldType: "hidden",
      label: "Parent Id",
      id: "cat_parent",
      class: "form-control1",
      name: "parentId",
      placeholder: "",
    },
    createdDate: {
      required: false,
      value: (dataArray.formData.createdDate !== undefined) ? dataArray.formData.createdDate : '',
      label: "Created Date",
      fieldType: "hidden",
      id: "created_date",
      class: "form-control1",
      name: "createdDate",
      placeholder: "",
    },
    modifiedDate: {
      required: false,
      value: (dataArray.formData.modifiedDate !== undefined) ? dataArray.formData.modifiedDate : '',
      label: "Update Date",
      fieldType: "hidden",
      id: "cat_modification_date",
      class: "form-control1",
      name: "modifiedDate",
      placeholder: "",
    },
    code: {
      required: true,
      value: ('code' in dataArray.formData) ? dataArray.formData.code : '',
      fieldType: "text",
      label: "Code",
      id: "cat_code",
      class: "form-control1",
      name: "code",
      placeholder: "Code",
    },
    name: {
      required: true,
      value: (dataArray.formData.name !== undefined) ? dataArray.formData.name : '',
      fieldType: "text",
      label: "Name",
      id: "cat_name",
      class: "form-control1",
      name: "name",
      placeholder: "Name",
    },
    description: {
      required: true,
      value: (dataArray.formData.description !== undefined) ? dataArray.formData.description : '',
      fieldType: "textarea",
      label: "Description",
      id: "cat_description",
      class: "form-control",
      name: "description",
      rows:4,
      cols:40,
      placeholder: "Description",
    },
    externalId: {
      required: true,
      value: (dataArray.formData.externalId !== undefined) ? dataArray.formData.externalId : '',
      label: "Update Date",
      label: "External  Id",
      fieldType: "text",
      id: "cat_external_id",
      class: "form-control1",
      name: "externalId",
      placeholder: "",
    },
    status: {
      required: true,
      value: (dataArray.formData.status !== undefined) ? dataArray.formData.status : '',
      fieldType: "select",
      label: "Status",
      optionArray: {
        0: "---------Please Select ------------------",
        1: "Active",
        2: "InActive",
      },
      id: "cat_active",
      class: "form-control1",
      name: "status",
      placeholder: "",
    },

    storeId: {
      required: true,
      value: (dataArray.formData.storeId !== undefined) ? dataArray.formData.storeId : '',
      label: "Store",
      fieldType: "select",
      id: "cat_store",
      optionArray: {
        0: "---------Please Select ------------------",
        1: "1",
        2: "2",
      },
      class: "form-control1",
      name: "storeId",
      placeholder: "",
    },
    updateRequired: {
      required: true,
      value: (dataArray.formData.updateRequired !== undefined) ? dataArray.formData.updateRequired : '',
      label: "Update  Required",
      fieldType: "select",
      id: "cat_update_req",
      optionArray: {
        0: "---------Please Select ------------------",
        1: "Yes",
        2: "No",
      },
      class: "form-control1",
      name: "updateRequired",
      placeholder: "",
    }, categoryImage: {
      required: false,
      value: (dataArray.formData.categoryImage !== undefined) ? dataArray.formData.categoryImage : '',
      label: "Category Image",
      id: "CategoryImage",
      fieldType: "upload",
      class: "form-control1",
      upload_path: '/admin/uploads/category_image/',
      name: "categoryImage",
      placeholder: "",
    },
    submit: {
      required: false,
      value: (dataArray.formData.submit !== undefined) ? dataArray.formData.submit : '',
      value: "Submit",
      label: "Submit",
      fieldType: "submit",
      id: "cat_submit",
      class: 'btn btn-default w3ls-button',
      name: "submit",
      placeholder: "",
    },
  };

  return form;
};



// create the model for users and expose it to our app
module.exports = {
  formArray: dynamicFormArray,
};
