const dynamicFormArray = (dataArray) => {
  form = {
    form: {
      required: false,
      method: "post",
      action: (dataArray.action !== undefined) ? dataArray.action : '',
      autocomplete: "off",
      //novalidate: "novalidate",
      class: "form-horizontal",
      enctype: "multipart/form-data",
    },
    _id: {
      required: false,
      value: ('_id' in dataArray.formData) ? dataArray.formData._id : '',
      fieldType: "hidden",
      id: "hexadecimal_id",
      name: "_id"
    },
    id: {
      required: true,
      value: ('id' in dataArray.formData) ? dataArray.formData.id : '',
      fieldType: "hidden",
      label: "Id",
      id: "prod_id",
      class: "form-control1",
      name: "id",
      placeholder: "",
    },
    sku: {
      required: true,
      value: ('sku' in dataArray.formData) ? dataArray.formData.sku : '',
      fieldType: "hidden",
      label: "Product sku",
      id: "sku",
      class: "form-control1",
      name: "sku",
      placeholder: "",
    },
    createdDate: {
      required: false,
      value: (dataArray.formData.createdDate !== undefined) ? dataArray.formData.createdDate : '',
      label: "Created Date",
      fieldType: "hidden",
      id: "created_date",
      class: "form-control1",
      name: "createdDate",
      placeholder: "",
    },
    modifiedDate: {
      required: false,
      value: (dataArray.formData.modifiedDate !== undefined) ? dataArray.formData.modifiedDate : '',
      label: "Update Date",
      fieldType: "hidden",
      id: "cat_modification_date",
      class: "form-control1",
      name: "modifiedDate",
      placeholder: "",
    },
    sku: {
      required: true,
      value: (dataArray.formData.sku !== undefined) ? dataArray.formData.sku : '',
      fieldType: "text",
      label: "Sku",
      id: "prod_code",
      class: "form-control1",
      name: "sku",
      placeholder: "Sku",
    },
    name: {
      required: true,
      value: (dataArray.formData.name !== undefined) ? dataArray.formData.name : '',
      fieldType: "text",
      label: "Name",
      id: "prod_name",
      class: "form-control1",
      name: "name",
      placeholder: "Name",
    },
    price: {
      required: true,
      value: ('price' in dataArray.formData) ? dataArray.formData.price : '',
      fieldType: "text",
      label: "Price",
      id: "prod_price",
      class: "form-control1",
      name: "price",
      placeholder: "1.00",
    },
    description: {
      required: true,
      value: (dataArray.formData.description !== undefined) ? dataArray.formData.description : '',
      fieldType: "textarea",
      label: "Description",
      id: "prod_description",
      rows: "4",
      cols: "50",
      class: "form-control",
      name: "description",
      placeholder: "Product Description",
    },
    categories: {
      required: true,
      value: ('categories' in dataArray.formData) ? dataArray.formData.categories : '',
      label: "Product Categories",
      fieldType: "multiselect",
      id: "prod_categories",
      optionArray: dataArray.formData.categoriesOption,
      class: "form-control1",
      name: "categories",
      placeholder: "",
    },
    bestseller: {
      required: false,
      value: (dataArray.formData.bestSeller !== undefined) ? dataArray.formData.bestSeller : '',
      fieldType: "checkbox",
      label: "Best Seller",
      id: "prod_bestseller",
      class: "product-slider",
      onchange :"updateStatus()",
      name: "bestseller",
      placeholder: "BestSeller",
    },
    newproduct: {
      required: false,
      value: (dataArray.formData.newProduct !== undefined) ? dataArray.formData.newProduct : '',
      fieldType: "checkbox",
      label: "New Product",
      id: "prod_newproduct",
      onchange :"updateStatus()",
      class: "product-slider",
      name: "newproduct",
      placeholder: "NewProduct",
    },
    crosssell: {
      required: false,
      value: (dataArray.formData.crossSell !== undefined) ? dataArray.formData.crossSell : '',
      fieldType: "checkbox",
      label: "Cross Sell",
      id: "prod_crosssell",
      onchange :"updateStatus()",
      class: "product-slider",
      name: "crosssell",
      placeholder: "Crosssell",
    },
    status: {
      required: false,
      value: (dataArray.formData.status !== undefined) ? dataArray.formData.status : '',
      fieldType: "select",
      label: "Status",
      optionArray: {
        0: "---------Please Select ------------------",
        1: "Active",
        2: "InActive",
      },
      id: "cat_active",
      class: "form-control1",
      name: "status",
      placeholder: "",
    },
    storeId: {
      required: true,
      value: (dataArray.formData.storeId !== undefined) ? dataArray.formData.storeId : '',
      label: "Store",
      fieldType: "select",
      id: "prod_store",
      optionArray: {
        0: "---------Please Select ------------------",
        1: "1",
        2: "2",
      },
      class: "form-control1",
      name: "storeId",
      placeholder: "",
    },
    updateRequired: {
      required: true,
      value: (dataArray.formData.updateRequired !== undefined) ? dataArray.formData.updateRequired : '',
      label: "Update  Required",
      fieldType: "select",
      id: "prod_update_req",
      optionArray: {
        0: "---------Please Select ------------------",
        1: "Yes",
        2: "No",
      },
      class: "form-control1",
      name: "updateRequired",
      placeholder: "",
    }, productGalleryImage: {
      required: false,
      value: (dataArray.formData.productGalleryImage !== undefined) ? dataArray.formData.productGalleryImage : '',
      label: "Product Image",
      id: "ProductImage",
      fieldType: "upload",
      class: "form-control1",
      upload_path: '/admin/uploads/product_images/',
      name: "productGalleryImage",
      placeholder: "",
    },
    submit: {
      required: false,
      value: (dataArray.formData.submit !== undefined) ? dataArray.formData.submit : '',
      value: "Submit",
      label: "Submit",
      fieldType: "submit",
      id: "prod_submit",
      class: 'btn btn-default w3ls-button',
      name: "submit",
      placeholder: "",
    },
  };

  return form;
};



// create the model for users and expose it to our app
module.exports = {
  formArray: dynamicFormArray,
};
